### ISSUE TITLE
ts-node compatibility

### ISSUE THREAD

**Issue by binary64** [TomerAberbach/get-all-files#5]
Hi,

Not sure this is the best place to ask, but I have this script.ts file:

```
import { getAllFilesSync } from "get-all-files";
getAllFilesSync(".")
```

and I run with ts-node script.ts but I get this error

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\p\monorepo\node_modules\get-all-files\src\index.js
require() of ES modules is not supported.
require() of C:\p\monorepo\node_modules\get-all-files\src\index.js from C:\p\monorepo\tools\cli\prepush.ts is an ES module file as it is a .js file whose nearest
 parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\p\monorepo\node_modules\get-all-files\package.j
son.
```

Do you have any ideas? I'm on ts-node v9

Many thanks

**Comment by TomerAberbach** [comment]
Hey!

So as of v4.0.0 `get-all-files` only publishes ESM (rather than CJS). If you're not familiar with the difference, then you can read about it on the [Node website](https://nodejs.org/api/esm.html), but I'll also give you a TL;DR:
- ESM is the newer module format that is now preferred over CJS.
- CJS cannot `require` ESM, but it can use dynamic import to import ESM asynchronously.
- ESM can import CJS without issue.

Back to your error: what's happening is `ts-node` is transpiling your TypeScript to CJS and the CJS tries to `require` `get-all-files` (which it can't do per my bullet points/the spec) so you get this error.

The solution would be either:
- Use dynamic import to import `get-all-files` asynchronously
- Configure `ts-node` to transpile to ESM (seems they have some [GitHub documentation](https://github.com/TypeStrong/ts-node#commonjs-vs-native-ecmascript-modules) on it) 

I hope that helps! Let me know if that solves your issue

**Comment by binary64** [comment]
Thank you for your detailed feedback. It felt like I was stuck down a rabbit hole.
